import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import React from 'react';
import { Document, Page, Text, View, Image, StyleSheet, pdf } from '@react-pdf/renderer';

// Define styles for PDF
const qrPdfStyles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#1F2937',
  },
  address: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 5,
  },
  qrContainer: {
    alignItems: 'center',
    marginVertical: 30,
    padding: 20,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
  },
  qrImage: {
    width: 300,
    height: 300,
    marginBottom: 15,
  },
  scanText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 10,
  },
  footer: {
    marginTop: 'auto',
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 10,
    color: '#9CA3AF',
    textAlign: 'center',
  },
});

// PDF Document Component
const QRStickerPDF = ({ qrUrl, address, city, state }: { qrUrl: string; address: string; city?: string; state?: string }) => (
  <Document>
    <Page size="A4" style={qrPdfStyles.page}>
      <View style={qrPdfStyles.header}>
        <Text style={qrPdfStyles.title}>HomeQR</Text>
        <Text style={qrPdfStyles.address}>{address}</Text>
        {(city || state) && (
          <Text style={qrPdfStyles.address}>
            {city && state ? `${city}, ${state}` : city || state}
          </Text>
        )}
      </View>
      <View style={qrPdfStyles.qrContainer}>
        <Image src={qrUrl} style={qrPdfStyles.qrImage} />
        <Text style={qrPdfStyles.scanText}>Scan to view property details</Text>
      </View>
      <View style={qrPdfStyles.footer}>
        <Text style={qrPdfStyles.footerText}>Generated by HomeQR</Text>
        <Text style={qrPdfStyles.footerText}>www.homeqr.com</Text>
      </View>
    </Page>
  </Document>
);

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: listingId } = await params;

    // Get listing and QR code
    const { data: listing, error: listingError } = await supabase
      .from('listings')
      .select('id, address, city, state, user_id, qrcodes(qr_url)')
      .eq('id', listingId)
      .eq('user_id', user.id)
      .single();

    if (listingError || !listing) {
      return NextResponse.json({ error: 'Listing not found' }, { status: 404 });
    }

    const qrCode = listing.qrcodes?.[0] as { qr_url: string } | undefined;

    if (!qrCode || !qrCode.qr_url) {
      return NextResponse.json({ error: 'QR code not found' }, { status: 404 });
    }

    // Generate PDF
    const pdfDoc = (
      <QRStickerPDF
        qrUrl={qrCode.qr_url}
        address={listing.address}
        city={listing.city || undefined}
        state={listing.state || undefined}
      />
    );

    // Use toBlob for browser/Node.js compatibility
    const pdfBlob = await pdf(pdfDoc).toBlob();
    const arrayBuffer = await pdfBlob.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Return PDF as response
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="homeqr-${listing.address.replace(/\s+/g, '-')}.pdf"`,
      },
    });
  } catch (error: unknown) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}

